export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

export type Month = (typeof MONTHS)[number];
export type Rating = 1 | 2 | 3 | 4 | 5;
export type Level = "Beginner" | "Intermediate" | "Advanced";
export type Region =
  | "North Pacific"
  | "Latin America + Caribbean"
  | "Europe + North Africa"
  | "Africa"
  | "Indian Ocean + Asia"
  | "Oceania";

export type SourceId =
  | "hawaii"
  | "trestles"
  | "malibu"
  | "mavericks"
  | "tofino"
  | "mexico"
  | "sayulita"
  | "scorpion-bay"
  | "costa-rica"
  | "nicaragua"
  | "el-salvador"
  | "ecuador"
  | "chicama"
  | "chile"
  | "brazil"
  | "barbados"
  | "france"
  | "spain"
  | "portugal"
  | "fistral"
  | "bundoran"
  | "morocco"
  | "senegal"
  | "jbay"
  | "skeleton-bay"
  | "bali"
  | "g-land"
  | "mentawais"
  | "nias"
  | "philippines"
  | "sri-lanka"
  | "maldives"
  | "fiji"
  | "queensland"
  | "victoria"
  | "western-australia"
  | "new-zealand"
  | "raglan"
  | "tahiti";

export interface SurfSource {
  id: SourceId;
  label: string;
  publisher: string;
  url: string;
}

export interface SurfSpot {
  id: string;
  name: string;
  place: string;
  country: string;
  region: Region;
  lat: number;
  lon: number;
  levels: Level[];
  breakType: string;
  direction: string;
  summary: string;
  seasonNote: string;
  conditions: string;
  caution: string;
  seasonality: readonly [
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
    Rating,
  ];
  sourceId: SourceId;
}

export const SOURCES: SurfSource[] = [
  {
    id: "hawaii",
    label: "Surfing in Hawaiʻi",
    publisher: "Go Hawaiʻi",
    url: "https://www.gohawaii.com/experiences/adventure/surfing",
  },
  {
    id: "trestles",
    label: "Spot Check: Lower Trestles",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-news/spot-check-lower-trestles/28785",
  },
  {
    id: "malibu",
    label: "Spot Check: Malibu",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-news/spot-check-malibu/26749",
  },
  {
    id: "mavericks",
    label: "Spot Check: Maverick’s",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-news/spot-check-mavericks/43920",
  },
  {
    id: "tofino",
    label: "Seasons in Tofino",
    publisher: "Tourism Tofino",
    url: "https://tourismtofino.com/about-tofino/seasons/",
  },
  {
    id: "mexico",
    label: "Puerto Escondido month-by-month",
    publisher: "Puerto Escondido",
    url: "https://www.puerto-escondido.mx/en/2026/01/27/best-time-to-visit-puerto-escondido-your-complete-month-by-month-guide/",
  },
  {
    id: "sayulita",
    label: "Sayulita, Nayarit",
    publisher: "Mexico Secretariat of Tourism",
    url: "https://www.gob.mx/sectur/es/articulos/sayulita-nayarit",
  },
  {
    id: "scorpion-bay",
    label: "San Juanico / Scorpion Bay surf guide",
    publisher: "Surfer",
    url: "https://www.surfer.com/culture/san-juanico-scorpion-bay-surf-guide-baja",
  },
  {
    id: "costa-rica",
    label: "When to visit Costa Rica",
    publisher: "Visit Costa Rica",
    url: "https://www.visitcostarica.com/plan-your-trip/when-to-visit",
  },
  {
    id: "nicaragua",
    label: "Popoyo Beach",
    publisher: "Visit Nicaragua",
    url: "https://www.visitanicaragua.com/en/playa-popoyo/",
  },
  {
    id: "el-salvador",
    label: "Punta Roca",
    publisher: "El Salvador Travel",
    url: "https://elsalvador.travel/esp/en/punta-roca/",
  },
  {
    id: "ecuador",
    label: "Ecuador’s Pacific Coast",
    publisher: "Ecuador Travel",
    url: "https://ecuador.travel/costa-del-pacifico/",
  },
  {
    id: "chicama",
    label: "Chicama seasonal overview",
    publisher: "Swell Archive",
    url: "https://swellarchive.com/surf-spot-statistics/chicama/580/",
  },
  {
    id: "chile",
    label: "Punta de Lobos",
    publisher: "Chile Travel",
    url: "https://chile.travel/atractivos/punta-de-lobos/",
  },
  {
    id: "brazil",
    label: "Joaquina spot guide",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-report/joaquina/5842041f4e65fad6a7708ceb",
  },
  {
    id: "barbados",
    label: "The Soup Bowl",
    publisher: "Visit Barbados",
    url: "https://www.visitbarbados.org/the-soup-bowl",
  },
  {
    id: "france",
    label: "Surfing in Hossegor",
    publisher: "Ultimate France",
    url: "https://www.ultimatefrance.com/surfing/south-west-france/hossegor",
  },
  {
    id: "spain",
    label: "Surfing in Euskadi",
    publisher: "Basque Country Tourism",
    url: "https://tourism.euskadi.eus/contenidos/recurso_tecnico/aa30_folletos/en_def/folletos/2020/Surfing_2020_EN_FR_web.pdf",
  },
  {
    id: "portugal",
    label: "Surfing in Central Portugal",
    publisher: "Visit Portugal",
    url: "https://www.visitportugal.com/en/content/surfing-in-the-center-of-portugal",
  },
  {
    id: "fistral",
    label: "Fistral Beach guide",
    publisher: "Cornwall Guide",
    url: "https://www.cornwall.co.uk/beach/fistral-beach/",
  },
  {
    id: "bundoran",
    label: "Surfing in Bundoran",
    publisher: "Discover Bundoran",
    url: "https://discoverbundoran.com/surfing/",
  },
  {
    id: "morocco",
    label: "Morocco Ocean & Wave",
    publisher: "Moroccan National Tourist Office",
    url: "https://www.visitmorocco.com/sites/default/files/atoms/files/maroc_ocean_wave_20250804_20251103_pbi_en.pdf",
  },
  {
    id: "senegal",
    label: "N’Gor season guide",
    publisher: "Travel Surf",
    url: "https://travel-surf.com/destination/senegal/",
  },
  {
    id: "jbay",
    label: "Jeffreys Bay surf spots",
    publisher: "Jeffreys Bay Tourism",
    url: "https://www.jeffreysbaytourism.co.za/2024/06/30/surf-spots/",
  },
  {
    id: "skeleton-bay",
    label: "Skeleton Bay spot guide",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-report/skeleton-bay/59b03873a36896001c177bc1/spot-guide",
  },
  {
    id: "bali",
    label: "Surfing adventures in Bali",
    publisher: "Visit Bali",
    url: "https://visitbali.com/experiences/surfing-adventures",
  },
  {
    id: "g-land",
    label: "Surfing G-Land",
    publisher: "Indonesia Travel",
    url: "https://www.indonesia.travel/gb/en/destination/java/east-java/surfing-g-land",
  },
  {
    id: "mentawais",
    label: "Macaronis spot guide",
    publisher: "Surfline",
    url: "https://www.surfline.com/surf-report/macaronis/5842041f4e65fad6a7708d36/spot-guide",
  },
  {
    id: "nias",
    label: "Surfing Lagundri Beach",
    publisher: "Indonesia Travel",
    url: "https://www.indonesia.travel/gb/en/destination/sumatra/north-sumatra/surfing-lagundri-beach",
  },
  {
    id: "philippines",
    label: "Cloud 9 surfing",
    publisher: "Love the Philippines",
    url: "https://philippines.travel/destinations/cloud-9-surfing/index",
  },
  {
    id: "sri-lanka",
    label: "Arugam Bay surf guide",
    publisher: "Visit Sri Lanka",
    url: "https://visitsrilanka.asia/blog/arugam-bay-surfing-guide",
  },
  {
    id: "maldives",
    label: "Surfing in the Maldives",
    publisher: "Visit Maldives",
    url: "https://visitmaldives.com/index.php/en/places/surfing-in-maldives",
  },
  {
    id: "fiji",
    label: "A first-timer’s guide to Cloudbreak",
    publisher: "Tourism Fiji",
    url: "https://www.fiji.travel/things-to-do/surfing/beginners-guide-to-surfing-cloudbreak",
  },
  {
    id: "queensland",
    label: "Where to surf in Queensland",
    publisher: "Queensland",
    url: "https://www.queensland.com/us/en/things-to-do/adventure/surfing/surfing-endless-stoke-best-surf-spots",
  },
  {
    id: "victoria",
    label: "Surfing the Great Ocean Road",
    publisher: "Visit Victoria",
    url: "https://www.visitvictoria.com/Regions/Great-Ocean-Road/See-and-do/Outdoor-and-adventure/Surfing-and-windsurfing",
  },
  {
    id: "western-australia",
    label: "Margaret River surfing itinerary",
    publisher: "Tourism Western Australia",
    url: "https://www.westernaustralia.com/en/itinerary/surfen-in-margaret-river/5ac5fb524ee5dff84dd50340",
  },
  {
    id: "new-zealand",
    label: "Surfing in New Zealand",
    publisher: "100% Pure New Zealand",
    url: "https://www.newzealand.com/nz/surfing/",
  },
  {
    id: "raglan",
    label: "Raglan seasonal overview",
    publisher: "Swell Archive",
    url: "https://swellarchive.com/surf-spot-statistics/raglan/501/",
  },
  {
    id: "tahiti",
    label: "When to visit Tahiti",
    publisher: "Tahiti Tourisme",
    url: "https://www.tahititourisme.com/preparing-you-trip/when-to-visit-the-islands-of-tahiti/",
  },
];

export const SURF_SPOTS: SurfSpot[] = [
  {
    id: "pipeline",
    name: "Banzai Pipeline",
    place: "Oʻahu, Hawaiʻi",
    country: "United States",
    region: "North Pacific",
    lat: 21.665,
    lon: -158.053,
    levels: ["Advanced"],
    breakType: "Shallow reef break",
    direction: "Left + right barrels",
    summary: "The benchmark for heavy, technical reef barrels on Oʻahu’s North Shore.",
    seasonNote: "North Pacific swell season builds in October, peaks November–February, and fades through April.",
    conditions: "Warm water year-round; winter brings the biggest surf, variable trades, and passing showers.",
    caution: "Expert-only when breaking: shallow reef, violent wipeouts, current, and an elite crowd.",
    seasonality: [5, 5, 4, 3, 2, 1, 1, 1, 2, 3, 4, 5],
    sourceId: "hawaii",
  },
  {
    id: "sunset-beach",
    name: "Sunset Beach",
    place: "Oʻahu, Hawaiʻi",
    country: "United States",
    region: "North Pacific",
    lat: 21.679,
    lon: -158.04,
    levels: ["Advanced"],
    breakType: "Open-ocean reef arena",
    direction: "Mostly rights",
    summary: "A sprawling, powerful North Shore lineup where reading the ocean is half the challenge.",
    seasonNote: "Most reliable from November through February, with strong early- and late-season shoulders.",
    conditions: "Warm tropical water offsets winter squalls; summer is pleasant but usually too small for the main break.",
    caution: "Long hold-downs, shifting peaks, heavy current, and a demanding paddle.",
    seasonality: [5, 5, 4, 3, 2, 1, 1, 1, 2, 3, 5, 5],
    sourceId: "hawaii",
  },
  {
    id: "waikiki",
    name: "Waikīkī",
    place: "Oʻahu, Hawaiʻi",
    country: "United States",
    region: "North Pacific",
    lat: 21.276,
    lon: -157.827,
    levels: ["Beginner", "Intermediate"],
    breakType: "Gentle reef breaks",
    direction: "Long rolling rights + lefts",
    summary: "Surfing’s classic classroom: warm water, long rides, and forgiving summer rollers.",
    seasonNote: "South swells favor May–September; winter is smaller on this side of Oʻahu.",
    conditions: "Sunny, warm, and accessible year-round, with the driest feel through the summer season.",
    caution: "Very crowded; mind reef shallows, canoes, swimmers, and right-of-way etiquette.",
    seasonality: [2, 2, 2, 3, 4, 5, 5, 5, 4, 3, 2, 2],
    sourceId: "hawaii",
  },
  {
    id: "honolua-bay",
    name: "Honolua Bay",
    place: "Maui, Hawaiʻi",
    country: "United States",
    region: "North Pacific",
    lat: 21.013,
    lon: -156.638,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef point break",
    direction: "Right",
    summary: "A beautifully groomed right that wraps into a sheltered, cliff-lined Maui bay.",
    seasonNote: "Needs winter north and northwest swells; December–February is the core window.",
    conditions: "Shelter can keep the face clean, while winter fronts bring occasional rain to lush West Maui.",
    caution: "Shallow sections, long paddle, rocks, and a concentrated takeoff crowd.",
    seasonality: [5, 5, 4, 3, 2, 1, 1, 1, 2, 3, 4, 5],
    sourceId: "hawaii",
  },
  {
    id: "jaws",
    name: "Peʻahi (Jaws)",
    place: "Maui, Hawaiʻi",
    country: "United States",
    region: "North Pacific",
    lat: 20.943,
    lon: -156.3,
    levels: ["Advanced"],
    breakType: "Deep-water reef break",
    direction: "Right + left",
    summary: "One of the world’s definitive big-wave stages, activated by major North Pacific swell.",
    seasonNote: "A rare-event wave centered on November–February rather than an everyday surf option.",
    conditions: "Winter is mild but wind and rain can accompany the systems that create the swell.",
    caution: "Elite big-wave teams only; rescue craft, specialized equipment, and local expertise are essential.",
    seasonality: [5, 5, 4, 2, 1, 1, 1, 1, 1, 2, 4, 5],
    sourceId: "hawaii",
  },
  {
    id: "lower-trestles",
    name: "Lower Trestles",
    place: "San Clemente, California",
    country: "United States",
    region: "North Pacific",
    lat: 33.383,
    lon: -117.588,
    levels: ["Intermediate", "Advanced"],
    breakType: "Cobblestone point",
    direction: "High-performance rights + lefts",
    summary: "Southern California’s most celebrated high-performance canvas, with near-symmetrical peaks.",
    seasonNote: "South swells build through spring and summer; late summer and fall often pair swell with clean winds.",
    conditions: "Dry, mild weather dominates; late summer offers the warmest water and fall often brings offshore mornings.",
    caution: "Long walk, intense crowd, and a high standard of lineup awareness.",
    seasonality: [2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 4, 3],
    sourceId: "trestles",
  },
  {
    id: "malibu",
    name: "Malibu First Point",
    place: "Malibu, California",
    country: "United States",
    region: "North Pacific",
    lat: 34.035,
    lon: -118.677,
    levels: ["Beginner", "Intermediate"],
    breakType: "Cobblestone point",
    direction: "Right",
    summary: "A historic, endlessly trim-friendly right that helped define modern longboarding.",
    seasonNote: "Summer south swells are the main event, with May–September the dependable planning window.",
    conditions: "Warm, dry summers and wind protection at First Point make for comfortable long sessions.",
    caution: "Extreme crowding and frequent collisions can make gentle waves deceptively hazardous.",
    seasonality: [2, 2, 2, 3, 4, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "malibu",
  },
  {
    id: "mavericks",
    name: "Mavericks",
    place: "Half Moon Bay, California",
    country: "United States",
    region: "North Pacific",
    lat: 37.495,
    lon: -122.5,
    levels: ["Advanced"],
    breakType: "Deep-water reef break",
    direction: "Right dominant",
    summary: "Cold-water California’s iconic big-wave test, holding immense long-period winter swell.",
    seasonNote: "The serious window runs November–March, with January and February most dependable.",
    conditions: "Cold water, short winter days, fog, and stormy intervals reward patient swell chasing.",
    caution: "Elite big-wave preparation, flotation, safety team, and local knowledge are mandatory.",
    seasonality: [5, 5, 4, 2, 1, 1, 1, 1, 1, 2, 4, 5],
    sourceId: "mavericks",
  },
  {
    id: "cox-bay",
    name: "Cox Bay",
    place: "Tofino, British Columbia",
    country: "Canada",
    region: "North Pacific",
    lat: 49.119,
    lon: -125.903,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Exposed beach break",
    direction: "Peaky rights + lefts",
    summary: "Canada’s cold-water surf hub, exposed to Pacific energy in a spectacular rainforest setting.",
    seasonNote: "Fall balances more consistent swell with manageable weather; winter turns powerful and stormy.",
    conditions: "A thick wetsuit is standard year-round; September–October offers the best weather-to-swell compromise.",
    caution: "Rips, drifting peaks, cold water, logs, and winter storm surf demand judgment.",
    seasonality: [2, 2, 3, 4, 4, 3, 3, 3, 4, 5, 4, 3],
    sourceId: "tofino",
  },
  {
    id: "sayulita",
    name: "Sayulita",
    place: "Nayarit",
    country: "Mexico",
    region: "North Pacific",
    lat: 20.868,
    lon: -105.441,
    levels: ["Beginner", "Intermediate"],
    breakType: "Beach + reef peaks",
    direction: "Mostly rights",
    summary: "A lively surf town with approachable rollers, rentals, lessons, and nearby options.",
    seasonNote: "Northwest swell and the dry season overlap from November through April.",
    conditions: "Warm water and sunny winter weather; summer is hotter, wetter, and less reliable at the town break.",
    caution: "Crowds, rocks near the point, and water quality after heavy rain.",
    seasonality: [5, 5, 5, 4, 3, 2, 2, 2, 2, 3, 4, 5],
    sourceId: "sayulita",
  },
  {
    id: "zicatela",
    name: "Zicatela",
    place: "Puerto Escondido, Oaxaca",
    country: "Mexico",
    region: "North Pacific",
    lat: 15.85,
    lon: -97.056,
    levels: ["Advanced"],
    breakType: "Heavy beach break",
    direction: "A-frame barrels",
    summary: "The Mexican Pipeline: powerful, shifting sandbar peaks fed by Southern Hemisphere swell.",
    seasonNote: "South swells arrive in April and run through October, with May–August the most dependable.",
    conditions: "Water stays warm; peak swell overlaps the humid rainy season, usually with cleaner mornings.",
    caution: "Severe hold-downs, strong current, board-breaking power, and changing sandbars.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 4, 4, 4, 3, 2],
    sourceId: "mexico",
  },
  {
    id: "scorpion-bay",
    name: "Scorpion Bay",
    place: "Baja California Sur",
    country: "Mexico",
    region: "North Pacific",
    lat: 26.235,
    lon: -112.48,
    levels: ["Intermediate", "Advanced"],
    breakType: "Series of point breaks",
    direction: "Long rights",
    summary: "Remote desert points that can link ruler-edged rights for extraordinary distance.",
    seasonNote: "Southern Hemisphere swells favor late spring through early fall, especially May–September.",
    conditions: "Dry desert weather is a plus; summer can be intensely hot and tropical systems occasionally intrude.",
    caution: "Remote access, limited services, rocks, currents, and long paddles between sections.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "scorpion-bay",
  },
  {
    id: "witchs-rock",
    name: "Witch’s Rock",
    place: "Guanacaste",
    country: "Costa Rica",
    region: "Latin America + Caribbean",
    lat: 10.837,
    lon: -85.699,
    levels: ["Intermediate", "Advanced"],
    breakType: "Remote beach break",
    direction: "Rights + lefts",
    summary: "A boat-accessed Costa Rican classic with clean peaks beside a dramatic volcanic sea stack.",
    seasonNote: "Dry-season offshore winds favor December–April; south swell keeps it active into the greener months.",
    conditions: "Warm water all year; May–November brings afternoon rain but often productive morning sessions.",
    caution: "Boat access, rips, crocodile habitat near river mouths, and no services on the beach.",
    seasonality: [5, 5, 5, 5, 4, 4, 4, 4, 4, 3, 3, 5],
    sourceId: "costa-rica",
  },
  {
    id: "pavones",
    name: "Pavones",
    place: "Puntarenas",
    country: "Costa Rica",
    region: "Latin America + Caribbean",
    lat: 8.395,
    lon: -83.136,
    levels: ["Intermediate", "Advanced"],
    breakType: "River-mouth point",
    direction: "Very long left",
    summary: "A leg-burning tropical left that can connect for hundreds of meters on a solid south swell.",
    seasonNote: "The south-swell engine is strongest April–October, with May–September most consistent.",
    conditions: "Peak waves coincide with the green season: humid, lush, rainy, and generally clean early.",
    caution: "Crowds, rocks, river runoff, long rides followed by long walks, and strong sweep.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "costa-rica",
  },
  {
    id: "popoyo",
    name: "Popoyo",
    place: "Rivas",
    country: "Nicaragua",
    region: "Latin America + Caribbean",
    lat: 11.469,
    lon: -86.128,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef break",
    direction: "Rights + lefts",
    summary: "A consistent reef peak backed by Nicaragua’s unusually reliable offshore wind machine.",
    seasonNote: "South swells run March–October; spring and early summer offer the strongest balance.",
    conditions: "Warm water year-round; wet-season afternoons can turn stormy while mornings stay offshore.",
    caution: "Shallow reef, current, urchins, and an outer reef that is expert-only when large.",
    seasonality: [3, 3, 4, 5, 5, 5, 5, 5, 5, 4, 3, 3],
    sourceId: "nicaragua",
  },
  {
    id: "punta-roca",
    name: "Punta Roca",
    place: "La Libertad",
    country: "El Salvador",
    region: "Latin America + Caribbean",
    lat: 13.488,
    lon: -89.321,
    levels: ["Advanced"],
    breakType: "Boulder point break",
    direction: "Right",
    summary: "A fast, sectioning world-class right with long walls and serious tropical power.",
    seasonNote: "South Pacific swells begin in March; March–July is strongest, with quality continuing into October.",
    conditions: "Warm water, hot air, and wet-season showers; clean morning winds are the usual target.",
    caution: "Submerged boulders, current, powerful sections, and a competitive takeoff zone.",
    seasonality: [2, 3, 5, 5, 5, 5, 5, 4, 4, 4, 3, 2],
    sourceId: "el-salvador",
  },
  {
    id: "montanita",
    name: "Montañita",
    place: "Santa Elena",
    country: "Ecuador",
    region: "Latin America + Caribbean",
    lat: -1.827,
    lon: -80.756,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Point + beach breaks",
    direction: "Right point + mixed peaks",
    summary: "A sociable Ecuadorian surf base where the beach teaches and La Punta adds power.",
    seasonNote: "North swells favor December–April while Southern Hemisphere energy supports the cooler middle months.",
    conditions: "December–April is warmer and sunnier; June–September is cooler, cloudier, and still wave-rich.",
    caution: "Busy lineups, rocks at the point, and strong currents when swell rises.",
    seasonality: [4, 5, 5, 5, 4, 4, 4, 4, 4, 3, 3, 4],
    sourceId: "ecuador",
  },
  {
    id: "chicama",
    name: "Chicama",
    place: "La Libertad Region",
    country: "Peru",
    region: "Latin America + Caribbean",
    lat: -7.704,
    lon: -79.451,
    levels: ["Intermediate"],
    breakType: "Desert point break",
    direction: "Exceptionally long left",
    summary: "A famously long, machine-like left with multiple sections along Peru’s arid north coast.",
    seasonNote: "Long-period south and southwest swells are most dependable March–September.",
    conditions: "Little rain, but cool Humboldt Current water, gray winter skies, and persistent wind require rubber.",
    caution: "Strong current, very long paddle, rocks, and fickle size despite the spot’s reputation.",
    seasonality: [2, 2, 4, 5, 5, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "chicama",
  },
  {
    id: "punta-de-lobos",
    name: "Punta de Lobos",
    place: "Pichilemu",
    country: "Chile",
    region: "Latin America + Caribbean",
    lat: -34.425,
    lon: -72.048,
    levels: ["Intermediate", "Advanced"],
    breakType: "Rocky point break",
    direction: "Left",
    summary: "Chile’s signature left, ranging from long walls to a legitimate big-wave arena.",
    seasonNote: "Southwest swell is strongest April–September; spring and fall soften the winter weather penalty.",
    conditions: "Cold water all year, with wet and chilly midwinter conditions and milder shoulder seasons.",
    caution: "Rock entry, current, cold water, kelp, and major consequences when the outer peaks activate.",
    seasonality: [3, 3, 4, 5, 4, 4, 4, 4, 5, 4, 3, 3],
    sourceId: "chile",
  },
  {
    id: "joaquina",
    name: "Praia da Joaquina",
    place: "Florianópolis",
    country: "Brazil",
    region: "Latin America + Caribbean",
    lat: -27.63,
    lon: -48.45,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Beach break",
    direction: "Rights + lefts",
    summary: "A storied Brazilian contest beach with shifting peaks and year-round surf culture.",
    seasonNote: "Autumn through spring is most consistent, with April–October the broad quality window.",
    conditions: "Winter brings stronger swell and cooler weather; fall and spring offer the friendliest compromise.",
    caution: "Rips, fast-changing sandbars, crowds, and powerful shorebreak on larger days.",
    seasonality: [3, 3, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3],
    sourceId: "brazil",
  },
  {
    id: "soup-bowl",
    name: "Soup Bowl",
    place: "Bathsheba",
    country: "Barbados",
    region: "Latin America + Caribbean",
    lat: 13.211,
    lon: -59.52,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef break",
    direction: "Right",
    summary: "A muscular, rippable Atlantic right with remarkable consistency and warm Caribbean water.",
    seasonNote: "North Atlantic swell favors November–April; September–October can receive tropical pulses.",
    conditions: "Warm year-round, with drier winter weather and stronger trade winds outside early mornings.",
    caution: "Shallow rock and reef, sea urchins, current, and a steep takeoff when solid.",
    seasonality: [5, 5, 5, 5, 3, 2, 2, 2, 3, 4, 5, 5],
    sourceId: "barbados",
  },
  {
    id: "hossegor",
    name: "Hossegor — La Gravière",
    place: "Landes",
    country: "France",
    region: "Europe + North Africa",
    lat: 43.663,
    lon: -1.445,
    levels: ["Advanced"],
    breakType: "Heavy beach break",
    direction: "Barreling rights + lefts",
    summary: "Europe’s premier sand-bottom tube factory when Atlantic swell meets the right banks.",
    seasonNote: "September and October combine returning Atlantic swell with warmer water and better weather.",
    conditions: "Summer is warm but often small and packed; winter is powerful, colder, and storm-prone.",
    caution: "Violent shorebreak, strong rips, changing banks, and extremely competitive peaks.",
    seasonality: [2, 2, 3, 4, 4, 4, 3, 3, 5, 5, 4, 3],
    sourceId: "france",
  },
  {
    id: "cote-des-basques",
    name: "Côte des Basques",
    place: "Biarritz",
    country: "France",
    region: "Europe + North Africa",
    lat: 43.477,
    lon: -1.567,
    levels: ["Beginner", "Intermediate"],
    breakType: "Beach + reef-fringed peaks",
    direction: "Mostly rights + lefts",
    summary: "A scenic birthplace of European surf culture with lessons, long walls, and a dramatic tidal beach.",
    seasonNote: "May–October is the useful travel window; September–October adds swell while retaining warmth.",
    conditions: "Pleasant summers and warm early fall water; winter systems are colder and less forgiving.",
    caution: "Beach disappears at high tide; rocks, crowds, and shifting currents require timing.",
    seasonality: [2, 2, 3, 4, 4, 5, 4, 4, 5, 5, 4, 3],
    sourceId: "france",
  },
  {
    id: "mundaka",
    name: "Mundaka",
    place: "Basque Country",
    country: "Spain",
    region: "Europe + North Africa",
    lat: 43.408,
    lon: -2.699,
    levels: ["Advanced"],
    breakType: "River-mouth sandbar",
    direction: "Long barreling left",
    summary: "A tidal, sand-bottom left that ranks among Europe’s most coveted waves when it aligns.",
    seasonNote: "Autumn is the prime target, with the most reliable window from October into early winter.",
    conditions: "Fall retains some warmth; winter is wetter, colder, and more exposed to storm disruption.",
    caution: "Fickle sandbar, narrow takeoff, strong current, rocks, and heavy crowd pressure.",
    seasonality: [4, 4, 3, 2, 2, 1, 1, 1, 4, 5, 5, 4],
    sourceId: "spain",
  },
  {
    id: "ribeira-dilhas",
    name: "Ribeira d’Ilhas",
    place: "Ericeira",
    country: "Portugal",
    region: "Europe + North Africa",
    lat: 38.987,
    lon: -9.419,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef point break",
    direction: "Right",
    summary: "A consistent, open-faced right at the heart of Europe’s only World Surfing Reserve.",
    seasonNote: "September–November is prime, while spring provides a more approachable shoulder window.",
    conditions: "Cool Atlantic water needs a wetsuit; early autumn balances swell, light winds, and sunny weather.",
    caution: "Rocky entry, urchins, current, and heavy crowding on quality days.",
    seasonality: [3, 3, 4, 4, 4, 3, 3, 3, 5, 5, 5, 4],
    sourceId: "portugal",
  },
  {
    id: "supertubos",
    name: "Supertubos",
    place: "Peniche",
    country: "Portugal",
    region: "Europe + North Africa",
    lat: 39.345,
    lon: -9.366,
    levels: ["Advanced"],
    breakType: "Heavy beach break",
    direction: "Barreling rights + lefts",
    summary: "Portugal’s celebrated sand-bottom barrel, with Peniche’s geography offering nearby wind options.",
    seasonNote: "Atlantic swell favors October–March, with October–November the weather-savvy peak.",
    conditions: "Fall is mild; winter delivers size but more wind, rain, and cold-water exposure.",
    caution: "Powerful closeouts, rips, shallow sandbar, and contest-level crowds.",
    seasonality: [4, 4, 4, 3, 2, 2, 2, 2, 4, 5, 5, 5],
    sourceId: "portugal",
  },
  {
    id: "arrifana",
    name: "Arrifana",
    place: "Aljezur, Algarve",
    country: "Portugal",
    region: "Europe + North Africa",
    lat: 37.294,
    lon: -8.865,
    levels: ["Beginner", "Intermediate"],
    breakType: "Sheltered beach break",
    direction: "Rights + lefts",
    summary: "A cliff-backed Algarve bay that offers shelter, surf schools, and a broad range of conditions.",
    seasonNote: "Autumn is strongest; its shelter keeps winter useful while summer leans smaller and friendlier.",
    conditions: "The Algarve is sunnier than northern Portugal, though Atlantic water stays cool.",
    caution: "Crowds, rips, rocks at the edges, and a shorebreak that intensifies with swell.",
    seasonality: [3, 3, 4, 4, 4, 4, 3, 3, 5, 5, 5, 4],
    sourceId: "portugal",
  },
  {
    id: "nazare",
    name: "Nazaré — Praia do Norte",
    place: "Leiria",
    country: "Portugal",
    region: "Europe + North Africa",
    lat: 39.61,
    lon: -9.085,
    levels: ["Advanced"],
    breakType: "Canyon-amplified beach break",
    direction: "Giant peaks",
    summary: "The world-famous big-wave amphitheater where an offshore canyon magnifies Atlantic swell.",
    seasonNote: "Big-wave alerts cluster October–March, with November–February the core chase window.",
    conditions: "Winter brings the swell and also rain, wind, cold water, and short daylight.",
    caution: "Elite tow and big-wave teams only; huge moving water, jet-ski traffic, and brutal shorebreak.",
    seasonality: [5, 5, 4, 2, 1, 1, 1, 1, 2, 4, 5, 5],
    sourceId: "portugal",
  },
  {
    id: "fistral",
    name: "Fistral Beach",
    place: "Newquay, Cornwall",
    country: "United Kingdom",
    region: "Europe + North Africa",
    lat: 50.416,
    lon: -5.101,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Exposed beach break",
    direction: "Rights + lefts",
    summary: "Britain’s best-known surf beach, with dependable exposure, schools, and contest pedigree.",
    seasonNote: "May, June, and September balance waves and weather; autumn adds power as temperatures fall.",
    conditions: "Cold-water gear is normal; summer is busiest and winter can be windy and raw.",
    caution: "Rips, crowds, fast tidal changes, and heavy winter surf.",
    seasonality: [3, 3, 4, 4, 5, 5, 3, 3, 5, 4, 3, 3],
    sourceId: "fistral",
  },
  {
    id: "bundoran",
    name: "Bundoran",
    place: "County Donegal",
    country: "Ireland",
    region: "Europe + North Africa",
    lat: 54.479,
    lon: -8.291,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Reef + beach breaks",
    direction: "Rights + lefts",
    summary: "Ireland’s surf capital, pairing serious reefs with learner beaches in a swell-rich pocket.",
    seasonNote: "September–November is the standout window; spring offers lighter, friendlier alternatives.",
    conditions: "Cold water and rapidly changing weather year-round; fall is the best balance before deep winter.",
    caution: "Shallow reefs, cold exposure, storm surf, currents, and large tidal ranges.",
    seasonality: [3, 3, 4, 4, 4, 3, 2, 3, 5, 5, 5, 4],
    sourceId: "bundoran",
  },
  {
    id: "anchor-point",
    name: "Anchor Point",
    place: "Taghazout",
    country: "Morocco",
    region: "Europe + North Africa",
    lat: 30.545,
    lon: -9.727,
    levels: ["Intermediate", "Advanced"],
    breakType: "Rocky point break",
    direction: "Long right",
    summary: "Morocco’s signature freight-train right, wrapping along a sun-baked Atlantic point.",
    seasonNote: "Consistent north Atlantic swell and mild weather overlap October–March.",
    conditions: "Sunny, mild, and comparatively warm in winter; summer is pleasant but often too small.",
    caution: "Rock entry, current, crowds, and fast sections on bigger swells.",
    seasonality: [5, 5, 5, 4, 3, 2, 2, 2, 2, 4, 5, 5],
    sourceId: "morocco",
  },
  {
    id: "imsouane",
    name: "Imsouane — The Bay",
    place: "Souss-Massa",
    country: "Morocco",
    region: "Europe + North Africa",
    lat: 30.84,
    lon: -9.821,
    levels: ["Beginner", "Intermediate"],
    breakType: "Sheltered point break",
    direction: "Very long right",
    summary: "A forgiving, endlessly long right that has become a global progression and longboard favorite.",
    seasonNote: "October–March is most consistent; smaller summer waves can suit learners and longboards.",
    conditions: "Mild, sunny coastal weather is a major draw; north winds are more persistent in summer.",
    caution: "Crowding, rocks near the takeoff, long paddle-backs, and local etiquette.",
    seasonality: [5, 5, 5, 4, 3, 3, 3, 3, 3, 4, 5, 5],
    sourceId: "morocco",
  },
  {
    id: "ngor-right",
    name: "N’Gor Right",
    place: "Dakar",
    country: "Senegal",
    region: "Europe + North Africa",
    lat: 14.75,
    lon: -17.515,
    levels: ["Intermediate", "Advanced"],
    breakType: "Island reef break",
    direction: "Right",
    summary: "The Endless Summer’s storied West African right, reached by pirogue from Dakar.",
    seasonNote: "North Atlantic swell favors November–March, with December–February the strongest period.",
    conditions: "Warm air and comfortable water meet dry-season weather during the best surf window.",
    caution: "Boat access, reef, current, urchins, and a small takeoff zone.",
    seasonality: [5, 5, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5],
    sourceId: "senegal",
  },
  {
    id: "jeffreys-bay",
    name: "Jeffreys Bay — Supertubes",
    place: "Eastern Cape",
    country: "South Africa",
    region: "Africa",
    lat: -34.05,
    lon: 24.93,
    levels: ["Intermediate", "Advanced"],
    breakType: "Point break",
    direction: "Fast right",
    summary: "A world-standard right point known for speed, flawless walls, and multiple connecting sections.",
    seasonNote: "Southern Ocean swell and favorable winds center the season on May–September.",
    conditions: "Peak surf arrives in cool, windy winter weather; a full wetsuit is standard.",
    caution: "Speed, rocks, current, cold water, sharks, and a world-class crowd.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "jbay",
  },
  {
    id: "skeleton-bay",
    name: "Skeleton Bay",
    place: "Walvis Bay",
    country: "Namibia",
    region: "Africa",
    lat: -23.113,
    lon: 14.452,
    levels: ["Advanced"],
    breakType: "Sand-bottom point",
    direction: "Ultra-long barreling left",
    summary: "A rare desert phenomenon capable of producing minute-long barrels along a shifting sand spit.",
    seasonNote: "The swell window is April–September, with June–August largest but never guaranteed.",
    conditions: "Cold Benguela water, fog, desert wind, and remote exposure make this a strike mission.",
    caution: "Extremely shallow barrels, relentless current, seals, sharks, isolation, and difficult access.",
    seasonality: [1, 1, 2, 4, 5, 5, 5, 5, 4, 2, 1, 1],
    sourceId: "skeleton-bay",
  },
  {
    id: "uluwatu",
    name: "Uluwatu",
    place: "Bali",
    country: "Indonesia",
    region: "Indian Ocean + Asia",
    lat: -8.829,
    lon: 115.085,
    levels: ["Intermediate", "Advanced"],
    breakType: "Multi-section reef",
    direction: "Left",
    summary: "Bali’s cliff-temple icon, offering several left-hand sections across a broad swell range.",
    seasonNote: "Indian Ocean swell and dry-season trade winds favor April–October, especially May–September.",
    conditions: "Warm water, low rainfall, and offshore southeast trades define the main season.",
    caution: "Sharp reef, strong current, cave access, tides, and a packed expert lineup.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 5, 4, 3],
    sourceId: "bali",
  },
  {
    id: "canggu",
    name: "Canggu",
    place: "Bali",
    country: "Indonesia",
    region: "Indian Ocean + Asia",
    lat: -8.659,
    lon: 115.13,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Beach + reef peaks",
    direction: "Rights + lefts",
    summary: "A dense cluster of Bali breaks, from mellow Batu Bolong rollers to punchier Echo Beach peaks.",
    seasonNote: "West-coast conditions are best April–October; wet-season winds and runoff lower reliability.",
    conditions: "Warm water always; the dry season is sunnier and cleaner, while wet season is humid and stormy.",
    caution: "Crowds, reef at some peaks, strong currents, and water quality after rain.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 5, 4, 3],
    sourceId: "bali",
  },
  {
    id: "g-land",
    name: "G-Land",
    place: "East Java",
    country: "Indonesia",
    region: "Indian Ocean + Asia",
    lat: -8.724,
    lon: 114.367,
    levels: ["Advanced"],
    breakType: "Multi-section reef point",
    direction: "Left",
    summary: "A remote jungle reef with a long sequence of powerful, high-quality left-hand sections.",
    seasonNote: "The official dry-season target is April–October, peaking across the middle months.",
    conditions: "Warm water, dry weather, and offshore trades align in season; access is expedition-like.",
    caution: "Shallow sharp reef, speed, current, marine life, and limited medical access.",
    seasonality: [1, 2, 3, 5, 5, 5, 5, 5, 5, 5, 4, 2],
    sourceId: "g-land",
  },
  {
    id: "macaronis",
    name: "Macaronis",
    place: "Mentawai Islands",
    country: "Indonesia",
    region: "Indian Ocean + Asia",
    lat: -2.147,
    lon: 99.989,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef point break",
    direction: "Left",
    summary: "A near-perfect, highly repeatable left with barrels, carve sections, and forgiving shape for its quality.",
    seasonNote: "March–October is dependable, with May–September carrying the most Southern Ocean energy.",
    conditions: "Tropical heat and warm water; dry-season winds vary by local storm and island exposure.",
    caution: "Reef, remote access, boat logistics, infection risk, and crowd pressure on charter days.",
    seasonality: [2, 2, 4, 5, 5, 5, 5, 5, 5, 5, 4, 2],
    sourceId: "mentawais",
  },
  {
    id: "nias",
    name: "Lagundri Bay",
    place: "Nias",
    country: "Indonesia",
    region: "Indian Ocean + Asia",
    lat: 0.571,
    lon: 97.748,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef point break",
    direction: "Right",
    summary: "A mechanically perfect tropical right with an easy channel and serious barrel when swell rises.",
    seasonNote: "Southern Hemisphere swell is strongest May–September, with useful shoulders on either side.",
    conditions: "Warm water all year; the drier middle months generally offer the cleanest travel window.",
    caution: "Shallow reef, powerful lip, crowds, and limited services beyond the surf village.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2],
    sourceId: "nias",
  },
  {
    id: "cloud-9",
    name: "Cloud 9",
    place: "Siargao",
    country: "Philippines",
    region: "Indian Ocean + Asia",
    lat: 9.812,
    lon: 126.166,
    levels: ["Advanced"],
    breakType: "Shallow reef break",
    direction: "Barreling right",
    summary: "The Philippines’ marquee wave: a compact, powerful right tube over very shallow reef.",
    seasonNote: "Pacific and typhoon swell peaks September–November; August and early winter form the shoulders.",
    conditions: "Warm water year-round; the prime swell window leads into the rainiest months.",
    caution: "Razor-sharp shallow reef, current, powerful barrels, and intense seasonal crowds.",
    seasonality: [2, 2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 3],
    sourceId: "philippines",
  },
  {
    id: "arugam-bay",
    name: "Arugam Bay",
    place: "Eastern Province",
    country: "Sri Lanka",
    region: "Indian Ocean + Asia",
    lat: 6.84,
    lon: 81.835,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Point + nearby beach breaks",
    direction: "Long rights",
    summary: "Sri Lanka’s east-coast surf capital, with a famous point and nearby waves for every stage.",
    seasonNote: "The east coast turns on April–October, with June–September the peak season.",
    conditions: "Warm water and mostly dry east-coast weather align while the southwest monsoon affects the opposite coast.",
    caution: "Crowds, rocks at Main Point, wildlife on access roads, heat, and strong midday wind.",
    seasonality: [1, 1, 2, 4, 5, 5, 5, 5, 5, 4, 2, 1],
    sourceId: "sri-lanka",
  },
  {
    id: "hikkaduwa",
    name: "Hikkaduwa",
    place: "Southern Province",
    country: "Sri Lanka",
    region: "Indian Ocean + Asia",
    lat: 6.139,
    lon: 80.099,
    levels: ["Beginner", "Intermediate", "Advanced"],
    breakType: "Reef + beach breaks",
    direction: "Rights + lefts",
    summary: "A compact southwest-coast surf zone with mellow beach waves and faster reef options.",
    seasonNote: "November–March brings the southwest coast’s dry weather and most favorable winds.",
    conditions: "Tropical warmth year-round; monsoon rain and onshore wind dominate the middle of the year.",
    caution: "Reef, urchins, crowds, boat traffic, and runoff after heavy rain.",
    seasonality: [5, 5, 5, 4, 2, 1, 1, 1, 1, 2, 4, 5],
    sourceId: "sri-lanka",
  },
  {
    id: "pasta-point",
    name: "Pasta Point",
    place: "North Malé Atoll",
    country: "Maldives",
    region: "Indian Ocean + Asia",
    lat: 4.314,
    lon: 73.592,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef point break",
    direction: "Left",
    summary: "A highly consistent Maldivian left with a clean barrel section and capped resort access.",
    seasonNote: "April–October is the surf season; June–August has the most swell while shoulder months can be glassier.",
    conditions: "Warm water always; peak swell overlaps the southwest monsoon’s wind and showers.",
    caution: "Private access rules, shallow reef, current, boat transfers, and limited equipment replacement.",
    seasonality: [2, 2, 4, 5, 4, 5, 5, 5, 5, 5, 3, 2],
    sourceId: "maldives",
  },
  {
    id: "snapper-rocks",
    name: "Snapper Rocks",
    place: "Gold Coast, Queensland",
    country: "Australia",
    region: "Oceania",
    lat: -28.165,
    lon: 153.55,
    levels: ["Intermediate", "Advanced"],
    breakType: "Sand-bottom point",
    direction: "Long right",
    summary: "The first engine of the Superbank, capable of linking exceptionally long, high-speed rights.",
    seasonNote: "Autumn and winter are the broad target: east and southeast swell is most dependable from April–September.",
    conditions: "Warm water and subtropical weather; cyclone-season rain and wind create both opportunity and disruption.",
    caution: "One of surfing’s densest crowds, fast sweep, rock jump, and very high performance level.",
    seasonality: [3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 3],
    sourceId: "queensland",
  },
  {
    id: "bells-beach",
    name: "Bells Beach",
    place: "Victoria",
    country: "Australia",
    region: "Oceania",
    lat: -38.369,
    lon: 144.281,
    levels: ["Intermediate", "Advanced"],
    breakType: "Reef + point breaks",
    direction: "Long rights",
    summary: "Australia’s most historic contest venue, delivering powerful open faces along the rugged Surf Coast.",
    seasonNote: "Autumn and winter bring the most dependable Southern Ocean swell, led by April–June.",
    conditions: "Cool water, brisk winds, and fast-changing Southern Ocean weather reward full cold-water gear.",
    caution: "Rock shelves, strong current, large swell, cold exposure, and busy event periods.",
    seasonality: [3, 3, 4, 5, 5, 5, 4, 4, 4, 3, 3, 3],
    sourceId: "victoria",
  },
  {
    id: "margaret-river",
    name: "Margaret River Main Break",
    place: "Western Australia",
    country: "Australia",
    region: "Oceania",
    lat: -33.972,
    lon: 114.988,
    levels: ["Advanced"],
    breakType: "Deep-water reef break",
    direction: "Right dominant",
    summary: "A powerful, open-ocean performance wave with size, consistency, and the feel of a natural stadium.",
    seasonNote: "Winter carries the most raw swell; March–May and September–November offer the best weather-adjusted balance.",
    conditions: "Mediterranean-climate winter brings rain, cool water, and frontal winds; fall is the gentler entry.",
    caution: "Heavy water, reef, currents, isolation between breaks, and sharks.",
    seasonality: [4, 4, 5, 5, 5, 4, 4, 4, 5, 5, 5, 4],
    sourceId: "western-australia",
  },
  {
    id: "raglan",
    name: "Raglan — Manu Bay",
    place: "Waikato",
    country: "New Zealand",
    region: "Oceania",
    lat: -37.824,
    lon: 174.803,
    levels: ["Intermediate", "Advanced"],
    breakType: "Boulder point break",
    direction: "Long left",
    summary: "A cinematic New Zealand left, with multiple points wrapping into a volcanic-black coast.",
    seasonNote: "Surf is possible year-round; March–May pairs dependable west swell with relatively settled weather.",
    conditions: "A wetsuit is usual; winter is colder and stormier, while summer is warmer but often smaller.",
    caution: "Rock entry, strong sweep, crowds, long paddle, and rapidly changing weather.",
    seasonality: [4, 4, 5, 5, 5, 4, 3, 3, 4, 4, 4, 4],
    sourceId: "raglan",
  },
  {
    id: "teahupoo",
    name: "Teahupoʻo",
    place: "Tahiti",
    country: "French Polynesia",
    region: "Oceania",
    lat: -17.847,
    lon: -149.267,
    levels: ["Advanced"],
    breakType: "Shallow pass reef",
    direction: "Left barrel",
    summary: "A uniquely thick, below-sea-level barrel that represents the absolute edge of paddle surfing.",
    seasonNote: "Southern Hemisphere swell and the drier season align May–October.",
    conditions: "Warm water year-round; the prime window is less humid and rain-prone than austral summer.",
    caution: "Elite-only shallow reef, extreme lip weight, boat traffic, current, and remote rescue logistics.",
    seasonality: [2, 2, 3, 4, 5, 5, 5, 5, 5, 5, 4, 2],
    sourceId: "tahiti",
  },
  {
    id: "cloudbreak",
    name: "Cloudbreak",
    place: "Mamanuca Islands",
    country: "Fiji",
    region: "Oceania",
    lat: -17.852,
    lon: 177.188,
    levels: ["Advanced"],
    breakType: "Outer reef break",
    direction: "Left",
    summary: "A remote, open-ocean reef left that scales from playful walls to one of surfing’s heaviest waves.",
    seasonNote: "Fijian winter, April–October, delivers the most consistent southwest swell.",
    conditions: "Warm water throughout; stronger trade winds occur in season, with mornings often the target.",
    caution: "Boat-only access, shallow reef, current, powerful swell, and no easy exit.",
    seasonality: [2, 2, 3, 5, 5, 5, 5, 5, 5, 5, 3, 2],
    sourceId: "fiji",
  },
];

export const REGIONS: Region[] = [
  "North Pacific",
  "Latin America + Caribbean",
  "Europe + North Africa",
  "Africa",
  "Indian Ocean + Asia",
  "Oceania",
];

export function getSource(sourceId: SourceId) {
  return SOURCES.find((source) => source.id === sourceId) ?? SOURCES[0];
}
